### ISSUE TITLE
this.getDetails is not a function

### ISSUE THREAD

**Issue by jakiepari** [PrinceKomali/twitter-url#1]
i try example code and get error

C:\Users\kanzaki\Downloads\node_modules\twitter-url\index.js:34
                let data = this.getDetails(id);
                                ^

TypeError: this.getDetails is not a function
    at getDetailsConcise (C:\Users\farih\Downloads\node_modules\twitter-url\index.js:34:19)
    at Object.<anonymous> (C:\Users\farih\Downloads\nt.js:3:15)

**Comment by koko-yl** [comment]
That is quite odd... I re-`npm install`-ed it and got the same problem, even though that shouldn't happen... odd
Nonetheless I've put out an update that should fix it; let me know if it does

**Comment by jakiepari** [comment]
I try again and work. Thank You!. Can You create facebook downloader?
